# Generated by Django 5.1.1 on 2025-08-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='steps_md',
            field=models.TextField(blank=True, null=True, verbose_name='Passo a passo (Markdown)'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('text', models.TextField(verbose_name='Instrução / Texto')),
                ('is_required', models.BooleanField(default=False, help_text='Se marcado, este passo é obrigatório')),
                ('completed', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='knowledge.process')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
