# Generated by Django 5.2.6 on 2025-09-11 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_alter_process_steps_md_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="steps_md",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Passo a passo (Rich Text)"
            ),
        ),
    ]
